version: '3'

services:
  openvpn:
    image: kylemanna/openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194"
    volumes:
      - ./openvpn:/etc/openvpn
    restart: always

  test_app:
    build:
      context: .
    depends_on:
      - openvpn
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TZ=Asia/Tomsk
    ports:
      - "80:80"
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - vpn-net

  test_pg:
    build:
      context: ./db
    depends_on:
      - openvpn
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - PGDATA=${PGDATA}
      - TZ=Asia/Tomsk
    ports:
      - "5432:5432"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vpn-net

volumes:
  postgres_data:
  vpn:
  certs:

networks:
  vpn-net:
    driver: bridge


